<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3oidc"
 *
 * Auto generated by Extension Builder 2021-02-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title'            => 'OpenID Connect authentication',
    'description'      => 'This extension provides an OpenID Connect authentication service for users.',
    'category'         => 'services',
    'author'           => 'Cyril Janody',
    'author_email'     => 'cyril.janody@fsg.ulaval.ca',
    'state'            => 'stable',
    'createDirs'       => '',
    'clearCacheOnLoad' => 0,
    'version'          => '1.0.0',
    'constraints'      => [
        'depends'   => [
            'typo3' => '9.5.0-',
        ],
        'conflicts' => [],
        'suggests'  => [],
    ],
    'autoload'         => [
        'psr-4' => ['FSG\\Oidc\\' => 'Classes'],
    ],
];
