services:
  FSG\Oidc\Listener\Core\Package\Event\AfterPackageActivationListener:
    tags:
      - name: event.listener
        identifier: t3oidcAfterPackageActivationListener
        event: TYPO3\CMS\Core\Package\Event\AfterPackageActivationEvent
